set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSTEM_PROCESSOR x86_64)

set(CMAKE_C_COMPILER x86_64-w64-mingw32-gcc)
set(CMAKE_CXX_COMPILER x86_64-w64-mingw32-g++)

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

set(SDL2_INCLUDE_DIRS /SDL/include)
set(SDL2_LIBRARIES /sdl-mingw/SDL2.dll)
set(RESOURCE_MK_COMMANDS
	ASEPRITE=aseprite
	GLSLANG=glslangValidator
	SPIRV_OPT=spirv-opt
	SPIRV_CROSS=spirv-cross
	NULL=/dev/null
)
