#define DRIFT_SUBSTEPS 4
#define DRIFT_PHYSICS_ITERATIONS 2

#define DRIFT_TICK_HZ 60.0f
#define DRIFT_SUBSTEP_HZ (DRIFT_TICK_HZ*DRIFT_SUBSTEPS)

#define DRIFT_PLAYER_COUNT 1
#define DRIFT_MAX_TOASTS 4

#define DRIFT_PLAYER_SPEED 300
#define DRIFT_QUICKSLOT_COUNT 4
#define DRIFT_PLAYER_CARGO_SLOT_COUNT 4
#define DRIFT_PLAYER_SIZE 14

#define DRIFT_POWER_BEAM_RADIUS (DRIFT_PLAYER_SIZE + 2)
#define DRIFT_POWER_EDGE_MIN_LENGTH 64
#define DRIFT_POWER_EDGE_MAX_LENGTH 192

#define DRIFT_MAX_BIOME 4
#define DRIFT_SPAWN_RADIUS 2048

#define DRIFT_HOME_POSITION ((DriftVec2){1330, -6050})
#define DRIFT_FACTORY_POSITION (DriftVec2){1049.778564f, -6024.318848f}

typedef enum {
	DRIFT_COLLISION_NONE,
	DRIFT_COLLISION_TERRAIN,
	DRIFT_COLLISION_PLAYER,
	DRIFT_COLLISION_ITEM,
	DRIFT_COLLISION_NON_HOSTILE,
	DRIFT_COLLISION_WORKER_DRONE,
	DRIFT_COLLISION_PLAYER_BULLET,
} DriftCollisionType;

typedef enum {
	DRIFT_BIOME_LIGHT,
	DRIFT_BIOME_RADIO,
	DRIFT_BIOME_CRYO,
	DRIFT_BIOME_DARK,
	DRIFT_BIOME_SPACE,
} DriftBiomeType;
