typedef enum {
	DRIFT_ITEM_TYPE_NONE,
	DRIFT_ITEM_TYPE_SCRAP,
	DRIFT_ITEM_TYPE_ORE,
	DRIFT_ITEM_TYPE_LUMIUM,
	DRIFT_ITEM_TYPE_POWER_SUPPLY,
	// DRIFT_ITEM_TYPE_CPU,
	DRIFT_ITEM_TYPE_OPTICS,
	DRIFT_ITEM_TYPE_HEADLIGHT,
	DRIFT_ITEM_TYPE_RUSTY_CANNON,
	DRIFT_ITEM_TYPE_CANNON,
	DRIFT_ITEM_TYPE_AUTOCANNON,
	DRIFT_ITEM_TYPE_POWER_NODE,
	DRIFT_ITEM_TYPE_MINING_LASER,
	// DRIFT_ITEM_TYPE_SMELTING_MODULE,
	// DRIFT_ITEM_TYPE_DRONE_CONTROLLER,
	// DRIFT_ITEM_TYPE_DRONE,
	_DRIFT_ITEM_TYPE_COUNT,
} DriftItemType;

typedef struct {
	const char* name;
	uint icon;
	bool cargo;
} DriftItem;

extern const DriftItem DRIFT_ITEMS[_DRIFT_ITEM_TYPE_COUNT];

typedef struct {
	uint type, count;
} DriftIngredient;

#define DRIFT_CRAFTABLE_MAX_INGREDIENTS 4

typedef struct {
	DriftIngredient ingredients[DRIFT_CRAFTABLE_MAX_INGREDIENTS];
} DriftCraftableItem;

extern const DriftCraftableItem DRIFT_CRAFTABLES[_DRIFT_ITEM_TYPE_COUNT];
